#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[216] =
    {   0,
        0,    0,    0,    0,   93,   91,   90,   89,   91,   87,
       91,   79,   80,   85,   83,   78,   84,   71,   70,   66,
       66,   66,   88,   76,   72,   86,   73,   68,   37,   68,
       68,   33,   29,   68,   68,   68,   35,   34,   36,   68,
       32,   31,   68,   68,   30,   68,   74,   75,   77,   81,
       82,   92,    0,   67,    0,    0,    0,    0,   70,   66,
       68,   68,   68,   68,   68,   68,   68,   56,   68,   68,
       68,   20,   68,   68,   68,   68,   68,   58,   68,   44,
       68,   68,   43,   68,   68,   68,   21,   68,   68,   68,
       68,   16,   68,   68,   68,   68,   68,   68,   68,   68,

       68,   57,   67,   69,   64,   65,   42,   15,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   48,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   46,   68,   18,   27,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   49,   68,   68,   47,   68,
       68,   68,   50,   68,   53,   17,   26,   62,   68,   59,
       22,   63,   68,   68,   61,   68,    6,   68,   68,   68,
       41,   38,   68,   68,   68,   68,   68,   55,   54,   28,
       68,   68,   39,   68,   45,   24,   13,   23,   68,    3,
       52,    7,   68,   19,   68,    9,   11,    4,   25,   68,

       68,   10,   12,   51,   14,   68,   40,    8,    1,   68,
        2,    5,   68,   60,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    1,    6,    4,    4,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   17,
       18,   16,   16,   16,   16,   16,   16,   19,   20,   21,
       22,   23,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       33,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,   52,   53,    1,   54,   55,   56,   57,

       58,   59,   60,   61,   62,   33,   63,   64,   65,   66,
       67,   68,   33,   69,   70,   71,   72,   73,   74,   75,
       76,   77,   78,    4,   79,    1,    1,    1,   33,    1,
        1,    1,    1,    1,    1,    1,   33,    1,    1,    1,
       33,    1,    1,    1,   33,    1,   33,    1,    1,    1,
        1,    1,    1,   33,    1,    1,    1,    1,    1,    1,
       33,    1,    1,    1,    1,    1,    1,    1,   33,    1,
        1,    1,   33,    1,    1,    1,   33,    1,   33,    1,
        1,    1,    1,    1,    1,   33,    1,    1,    1,    1,
        1,    1,    1,    1,   33,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[80] =
    {   0,
        1,    2,    2,    2,    2,    1,    1,    2,    2,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    4,
        1,    1,    5,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[222] =
    {   0,
        0,    0,    0,    0,  104, 1534, 1534, 1534,   75, 1534,
       65, 1534, 1534, 1534, 1534, 1534, 1534, 1534,    0,   68,
       71,   74, 1534, 1534, 1534, 1534, 1534,   78,   81,  125,
       95,  101,  178,  120,   91,  134,  150,  196,  207,  164,
      212,  271,  251,  259,  255,  301, 1534, 1534, 1534, 1534,
     1534, 1534,   96,   97,   43,  167,  183,  154,    0,  226,
      237,  284,  315,  323,  328,  331,  334,  341,  353,  362,
      372,  349,  395,  387,  400,  415,  425,  357,  429,  444,
      453,  457,  463,  473,  528,  484,  495,  513,  522,  545,
      566,  580,  551,  596,  608,  626,  612,  629,  642,  653,

      646,  506, 1534, 1534,  659,  671,  676,  684,  700,  705,
      709,  714,  717,  731,  734,  748,  761,  772,  764,  780,
      777,  792,  802,  810,  830,  836,  841,  849,  854,  858,
      881,  887,  897,  905,  908,  913,  920,  928,  937,  946,
      959,  931,  953,  975,  986,  992, 1003, 1007, 1016, 1019,
     1024, 1036, 1032, 1046, 1050, 1062, 1066, 1074, 1077, 1088,
     1080, 1091, 1105, 1096, 1119, 1129, 1134, 1139, 1143, 1147,
     1157, 1163, 1177, 1185, 1203, 1197, 1206, 1209, 1215, 1223,
     1235, 1253, 1262, 1265, 1269, 1273, 1276, 1279, 1282, 1291,
     1295, 1303, 1307, 1320, 1329, 1334, 1337, 1341, 1348, 1351,

     1354, 1358, 1367, 1379, 1382, 1396, 1405, 1408, 1411, 1423,
     1426, 1429, 1434, 1437, 1534, 1510, 1515, 1518, 1522, 1525,
     1528
    } ;

static yyconst flex_int16_t yy_def[222] =
    {   0,
      215,    1,  216,  216,  215,  215,  215,  215,  217,  215,
      218,  215,  215,  215,  215,  215,  215,  215,  219,  220,
      220,  220,  215,  215,  215,  215,  215,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  215,  215,  215,  215,
      215,  215,  217,  215,  217,  215,  218,  218,  219,  220,
      220,  220,  220,  220,  220,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,   85,  221,  221,  221,  221,  221,  221,  221,  221,

      221,  221,  215,  215,  220,  220,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,

      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,    0,  215,  215,  215,  215,  215,
      215
    } ;

static yyconst flex_uint16_t yy_nxt[1614] =
    {   0,
        6,    7,    8,    6,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   35,   37,   38,   39,   40,   35,   41,   42,
       43,   44,   45,   35,   46,   35,   35,   35,   47,    6,
       48,   49,    6,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   35,   41,   42,   43,
       44,   45,   35,   46,   35,   35,   35,   50,   51,   54,
       56,   56,   56,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   55,   65,   65,   65,   65,   65,   65,   63,

       54,  103,   64,  215,   67,  215,   65,   65,   65,   68,
       65,   65,   65,  215,   58,  215,   65,   65,   65,  215,
       62,  215,   73,   62,   55,  215,   62,   74,  215,   63,
       62,  215,   64,   62,   67,   65,   65,   65,  215,   68,
       65,   65,   65,   62,  215,   55,   75,   62,   69,   65,
       65,   65,   73,   62,  215,   70,  215,   74,  215,   82,
       83,  215,   71,   72,  215,   65,   65,   65,  215,   56,
       56,   56,   62,  104,  215,   75,  215,   62,   69,   65,
       65,   65,   56,   56,   56,   70,   62,   88,   82,  104,
       83,   71,   72,   65,   65,   65,  215,  215,  215,  215,

      215,   76,   62,  215,   77,  215,   78,  215,  215,   79,
      215,   65,   65,   65,  215,  215,   62,   88,   80,  215,
       81,  215,   65,   65,   65,  215,  215,   65,   65,   65,
       62,   76,  215,   84,   77,   89,   78,  215,  215,   79,
       85,   60,   60,   60,   86,  215,  215,   80,   62,   81,
       87,  215,   65,   65,   65,  215,   90,  215,  215,   62,
      215,  215,   84,  215,   62,   89,   65,   65,   65,   85,
       65,   65,   65,   86,   65,   65,   65,  215,   62,   87,
      215,  215,   95,  215,   99,   90,   65,   65,   65,   62,
      100,  215,   96,  215,  215,  101,   97,  215,   91,   65,

       65,   65,  215,   62,  215,   98,   92,   62,   93,  215,
      215,   62,   95,   94,   99,  215,   65,   65,   65,  100,
      215,   96,  215,   62,  101,   97,  215,  215,   91,  102,
       65,   65,   65,  215,   98,   92,   62,   93,   65,   65,
       65,  215,   94,   65,   65,   65,   65,   65,   65,   65,
       65,   65,  215,   62,  215,  105,   65,   65,   65,  102,
      107,  215,  215,  106,   65,   65,   65,   62,   65,   65,
       65,  215,   65,   65,   65,   62,  215,   65,   65,   65,
       62,  215,  215,   62,  105,  215,   62,   65,   65,   65,
      107,  109,  106,   62,  108,  215,  215,  110,  215,  111,

      215,   62,   65,   65,   65,   62,  215,  215,  112,   62,
       65,   65,   65,  215,   62,   65,   65,   65,  115,  215,
      215,  109,  215,  108,   62,  215,  110,  116,  111,  113,
       65,   65,   65,  215,  215,  114,  215,  112,  215,   62,
       65,   65,   65,  215,   65,   65,   65,   62,  115,  215,
      215,  215,   62,  215,  215,  117,  118,  116,  113,   65,
       65,   65,  215,  119,  114,  120,  215,   62,   65,   65,
       65,  215,   65,   65,   65,  215,  215,   62,   65,   65,
       65,   62,  215,  215,  117,  215,  118,  121,   65,   65,
       65,  215,  119,  215,  120,  122,   62,  215,  215,   65,

       65,   65,  123,  215,  215,   62,  215,  215,  215,   62,
       65,   65,   65,  124,  215,   62,  121,  215,  215,  215,
      215,   65,   65,   65,  122,   62,  129,  215,   65,   65,
       65,  215,  123,  215,  215,  215,   62,   65,   65,   65,
      215,  215,  124,   65,   65,   65,  215,   62,  130,  215,
      215,  215,  215,  215,  125,  129,  126,  127,   62,  215,
       65,   65,   65,  131,  132,   62,   65,   65,   65,  215,
      128,  133,  215,  215,   62,  215,  215,  130,  215,  215,
       62,   65,   65,   65,  125,  215,  126,  127,  140,  215,
      215,  134,  131,  132,  215,  215,  215,   62,  215,  128,

      215,  133,  135,   62,  136,  215,  137,  215,   66,  138,
      215,   65,   65,   65,  215,  215,  215,  140,   62,  215,
      215,  134,  139,   65,   65,   65,  215,   65,   65,   65,
      215,  135,  215,  136,  215,  215,  137,  141,   66,  138,
      215,   65,   65,   65,   65,   65,   65,  215,   62,  215,
      215,  139,  143,  215,  144,  142,  215,   65,   65,   65,
       62,   65,   65,   65,   62,  215,  141,  145,   65,   65,
       65,  215,  215,  148,   65,   65,   65,  215,   62,  146,
      215,   62,  143,  144,  142,  149,   65,   65,   65,  215,
      147,   65,   65,   65,   62,  215,  145,  215,   62,   65,

       65,   65,  215,  148,  215,   62,  215,  215,  146,  215,
      215,   62,  215,  215,  149,   65,   65,   65,  215,  147,
       65,   65,   65,   62,   65,   65,   65,  215,   62,   65,
       65,   65,   65,   65,   65,  215,   62,  215,  215,  150,
      215,  215,  151,  215,  154,  215,   65,   65,   65,   65,
       65,   65,   62,  152,  215,  153,  215,   62,  215,  215,
      215,   62,  215,   65,   65,   65,   62,  215,  150,   62,
      215,  151,  155,  157,  154,  156,   65,   65,   65,   65,
       65,   65,  152,   62,  153,  215,   62,   65,   65,   65,
      215,  160,   65,   65,   65,   65,   65,   65,  215,  215,

       62,  155,  158,  157,  156,  215,  161,   65,   65,   65,
      215,  162,  159,   62,  215,  215,   62,   65,   65,   65,
      215,  160,  215,  215,   62,   65,   65,   65,  215,   62,
      215,  158,   62,  163,  215,  215,  161,  215,  215,  164,
      162,  159,  215,  215,   62,   65,   65,   65,  215,  215,
      165,   65,   65,   65,   62,  215,   65,   65,   65,  215,
      215,  166,   62,  163,   65,   65,   65,  215,  164,   65,
       65,   65,  215,   65,   65,   65,  167,  215,  215,  165,
      168,  215,   62,  215,  215,  171,  215,  215,   62,  169,
      170,  166,  215,   62,  215,  215,   65,   65,   65,  215,

      215,   62,   65,   65,   65,  167,   62,  215,  215,  168,
       62,  172,   65,   65,   65,  171,  215,  215,  169,  170,
       65,   65,   65,   65,   65,   65,  215,  173,   65,   65,
       65,  215,  215,   62,  215,   65,   65,   65,  215,   62,
      215,  172,  174,   65,   65,   65,   65,   65,   65,   62,
      215,  175,   65,   65,   65,  215,  173,   62,  180,  215,
       62,   65,   65,   65,  215,   62,  215,  176,   65,   65,
       65,  174,   62,  215,   65,   65,   65,  177,  215,  215,
       62,  175,  179,   62,  181,  215,  215,  178,  180,   62,
       65,   65,   65,  215,  215,  215,  176,  215,   62,  215,

      182,   65,   65,   65,  215,   62,  177,   65,   65,   65,
      215,   62,  179,  183,  181,  215,  178,  215,   65,   65,
       65,  215,   65,   65,   65,  215,  215,   62,  215,  215,
      182,   65,   65,   65,   65,   65,   65,  215,   62,   65,
       65,   65,  215,  183,   62,  184,  185,   65,   65,   65,
      187,   65,   65,   65,  215,   62,  215,  186,  215,   62,
      215,   65,   65,   65,  215,   65,   65,   65,   62,  215,
      215,   62,  188,  215,  184,  185,   62,   65,   65,   65,
      187,   65,   65,   65,   62,  215,  186,  189,   62,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   62,  215,

      215,  188,   62,   65,   65,   65,   65,   65,   65,  215,
      190,   65,   65,   65,   62,  215,  189,  215,   62,  215,
       65,   65,   65,  215,  191,  215,   62,  215,  215,   62,
      215,  215,   62,  215,   65,   65,   65,  215,  193,  190,
       62,  192,  215,   62,   65,   65,   65,  215,   62,   65,
       65,   65,  215,  191,   65,   65,   65,   62,   65,   65,
       65,  215,   65,   65,   65,  215,  215,  193,  194,  195,
      192,   62,   65,   65,   65,  215,  215,  196,   65,   65,
       65,   62,  197,  215,  215,  215,   62,  215,  198,  215,
      215,   62,   65,   65,   65,   62,  215,  194,  195,   62,

       65,   65,   65,  215,  199,  215,  196,  215,  215,   62,
      215,  197,   65,   65,   65,   62,  215,  198,   65,   65,
       65,   65,   65,   65,   65,   65,   65,  215,  200,   62,
       65,   65,   65,  215,  199,  202,  215,   62,   65,   65,
       65,  215,  215,  201,  215,  203,  215,  215,  215,   62,
       65,   65,   65,  215,  215,   62,  215,  200,   62,  215,
      215,   62,  215,  215,  202,  215,  215,   62,   65,   65,
       65,  204,  201,  215,  203,   62,  215,   65,   65,   65,
       65,   65,   65,  205,   65,   65,   65,   62,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,

      204,  206,  215,  215,  215,   62,   65,   65,   65,  207,
       65,   65,   65,  205,   62,  215,  215,   62,   65,   65,
       65,   62,   65,   65,   65,   62,  215,  215,   62,  215,
      206,   62,  215,  215,   62,   65,   65,   65,  215,  207,
      215,  215,  215,   62,   65,   65,   65,   62,  208,   65,
       65,   65,   65,   65,   65,   62,   65,   65,   65,   62,
      215,  215,  209,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   62,   65,   65,   65,  215,  208,  210,  215,
      215,   62,   65,   65,   65,  215,   62,  211,  215,   62,
      215,  209,  215,   62,   65,   65,   65,   65,   65,   65,

       62,  215,  215,   62,  215,  215,   62,  215,  210,  215,
       62,   65,   65,   65,  215,  215,  211,  215,  215,   62,
       65,   65,   65,   65,   65,   65,   65,   65,   65,  215,
      215,   62,  215,  215,   62,  215,  215,  212,   65,   65,
       65,   65,   65,   65,   65,   65,   65,  215,   62,   65,
       65,   65,   65,   65,   65,  215,  215,   62,  215,  215,
       62,  215,  213,   62,  215,  215,  212,  215,  215,  215,
      215,  215,  215,  215,  215,   62,  215,  215,   62,  215,
      214,   62,  215,  215,  215,  215,   62,  215,  215,   62,
      215,  213,  215,  215,  215,  215,  215,  215,  215,  215,

      215,  215,  215,  215,  215,  215,  215,  215,  215,  214,
       52,   52,   52,   52,   52,   53,   53,   53,   53,   53,
       57,   57,   59,  215,   59,   59,   59,   61,  215,   61,
       66,  215,   66,    5,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,

      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215
    } ;

static yyconst flex_int16_t yy_chk[1614] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    9,
       11,   11,   11,   20,   20,   20,   21,   21,   21,   22,
       22,   22,   55,   28,   28,   28,   29,   29,   29,   21,

       53,   54,   22,    5,   28,    0,   35,   35,   35,   29,
       31,   31,   31,    0,   11,    0,   32,   32,   32,    0,
       20,    0,   31,   21,    9,    0,   22,   32,    0,   21,
       28,    0,   22,   29,   28,   34,   34,   34,    0,   29,
       30,   30,   30,   35,    0,   53,   32,   31,   30,   36,
       36,   36,   31,   32,    0,   30,    0,   32,    0,   34,
       36,    0,   30,   30,    0,   37,   37,   37,    0,   58,
       58,   58,   34,   56,    0,   32,    0,   30,   30,   40,
       40,   40,   56,   56,   56,   30,   36,   40,   34,   57,
       36,   30,   30,   33,   33,   33,    0,    0,   57,   57,

       57,   33,   37,   58,   33,    0,   33,    0,    0,   33,
        0,   38,   38,   38,    0,    0,   40,   40,   33,    0,
       33,    0,   39,   39,   39,    0,    0,   41,   41,   41,
       33,   33,   57,   38,   33,   41,   33,    0,    0,   33,
       39,   60,   60,   60,   39,    0,    0,   33,   38,   33,
       39,    0,   61,   61,   61,    0,   41,    0,    0,   39,
        0,    0,   38,    0,   41,   41,   43,   43,   43,   39,
       45,   45,   45,   39,   44,   44,   44,    0,   60,   39,
        0,    0,   43,    0,   45,   41,   42,   42,   42,   61,
       45,    0,   43,    0,    0,   45,   44,    0,   42,   62,

       62,   62,    0,   43,    0,   44,   42,   45,   42,    0,
        0,   44,   43,   42,   45,    0,   46,   46,   46,   45,
        0,   43,    0,   42,   45,   44,    0,    0,   42,   46,
       63,   63,   63,    0,   44,   42,   62,   42,   64,   64,
       64,    0,   42,   65,   65,   65,   66,   66,   66,   67,
       67,   67,    0,   46,    0,   63,   68,   68,   68,   46,
       67,    0,    0,   64,   72,   72,   72,   63,   69,   69,
       69,    0,   78,   78,   78,   64,    0,   70,   70,   70,
       65,    0,    0,   66,   63,    0,   67,   71,   71,   71,
       67,   70,   64,   68,   69,    0,    0,   70,    0,   70,

        0,   72,   74,   74,   74,   69,    0,    0,   71,   78,
       73,   73,   73,    0,   70,   75,   75,   75,   74,    0,
        0,   70,    0,   69,   71,    0,   70,   75,   70,   73,
       76,   76,   76,    0,    0,   73,    0,   71,    0,   74,
       77,   77,   77,    0,   79,   79,   79,   73,   74,    0,
        0,    0,   75,    0,    0,   76,   77,   75,   73,   80,
       80,   80,    0,   79,   73,   79,    0,   76,   81,   81,
       81,    0,   82,   82,   82,    0,    0,   77,   83,   83,
       83,   79,    0,    0,   76,    0,   77,   81,   84,   84,
       84,    0,   79,    0,   79,   82,   80,    0,    0,   86,

       86,   86,   84,    0,    0,   81,    0,    0,    0,   82,
       87,   87,   87,   84,    0,   83,   81,    0,    0,    0,
        0,  102,  102,  102,   82,   84,   86,    0,   88,   88,
       88,    0,   84,    0,    0,    0,   86,   89,   89,   89,
        0,    0,   84,   85,   85,   85,    0,   87,   88,    0,
        0,    0,    0,    0,   85,   86,   85,   85,  102,    0,
       90,   90,   90,   89,   89,   88,   93,   93,   93,    0,
       85,   90,    0,    0,   89,    0,    0,   88,    0,    0,
       85,   91,   91,   91,   85,    0,   85,   85,   93,    0,
        0,   91,   89,   89,    0,    0,    0,   90,    0,   85,

        0,   90,   91,   93,   91,    0,   92,    0,   92,   92,
        0,   94,   94,   94,    0,    0,    0,   93,   91,    0,
        0,   91,   92,   95,   95,   95,    0,   97,   97,   97,
        0,   91,    0,   91,    0,    0,   92,   94,   92,   92,
        0,   96,   96,   96,   98,   98,   98,    0,   94,    0,
        0,   92,   96,    0,   97,   95,    0,   99,   99,   99,
       95,  101,  101,  101,   97,    0,   94,   98,  100,  100,
      100,    0,    0,  101,  105,  105,  105,    0,   96,   99,
        0,   98,   96,   97,   95,  101,  106,  106,  106,    0,
      100,  107,  107,  107,   99,    0,   98,    0,  101,  108,

      108,  108,    0,  101,    0,  100,    0,    0,   99,    0,
        0,  105,    0,    0,  101,  109,  109,  109,    0,  100,
      110,  110,  110,  106,  111,  111,  111,    0,  107,  112,
      112,  112,  113,  113,  113,    0,  108,    0,    0,  109,
        0,    0,  110,    0,  113,    0,  114,  114,  114,  115,
      115,  115,  109,  111,    0,  112,    0,  110,    0,    0,
        0,  111,    0,  116,  116,  116,  112,    0,  109,  113,
        0,  110,  114,  116,  113,  115,  117,  117,  117,  119,
      119,  119,  111,  114,  112,    0,  115,  118,  118,  118,
        0,  119,  121,  121,  121,  120,  120,  120,    0,    0,

      116,  114,  117,  116,  115,    0,  120,  122,  122,  122,
        0,  121,  118,  117,    0,    0,  119,  123,  123,  123,
        0,  119,    0,    0,  118,  124,  124,  124,    0,  121,
        0,  117,  120,  123,    0,    0,  120,    0,    0,  123,
      121,  118,    0,    0,  122,  125,  125,  125,    0,    0,
      124,  126,  126,  126,  123,    0,  127,  127,  127,    0,
        0,  125,  124,  123,  128,  128,  128,    0,  123,  129,
      129,  129,    0,  130,  130,  130,  126,    0,    0,  124,
      127,    0,  125,    0,    0,  130,    0,    0,  126,  128,
      129,  125,    0,  127,    0,    0,  131,  131,  131,    0,

        0,  128,  132,  132,  132,  126,  129,    0,    0,  127,
      130,  131,  133,  133,  133,  130,    0,    0,  128,  129,
      134,  134,  134,  135,  135,  135,    0,  132,  136,  136,
      136,    0,    0,  131,    0,  137,  137,  137,    0,  132,
        0,  131,  134,  138,  138,  138,  142,  142,  142,  133,
        0,  137,  139,  139,  139,    0,  132,  134,  142,    0,
      135,  140,  140,  140,    0,  136,    0,  138,  143,  143,
      143,  134,  137,    0,  141,  141,  141,  139,    0,    0,
      138,  137,  141,  142,  143,    0,    0,  140,  142,  139,
      144,  144,  144,    0,    0,    0,  138,    0,  140,    0,

      144,  145,  145,  145,    0,  143,  139,  146,  146,  146,
        0,  141,  141,  145,  143,    0,  140,    0,  147,  147,
      147,    0,  148,  148,  148,    0,    0,  144,    0,    0,
      144,  149,  149,  149,  150,  150,  150,    0,  145,  151,
      151,  151,    0,  145,  146,  147,  148,  153,  153,  153,
      151,  152,  152,  152,    0,  147,    0,  150,    0,  148,
        0,  154,  154,  154,    0,  155,  155,  155,  149,    0,
        0,  150,  152,    0,  147,  148,  151,  156,  156,  156,
      151,  157,  157,  157,  153,    0,  150,  154,  152,  158,
      158,  158,  159,  159,  159,  161,  161,  161,  154,    0,

        0,  152,  155,  160,  160,  160,  162,  162,  162,    0,
      159,  164,  164,  164,  156,    0,  154,    0,  157,    0,
      163,  163,  163,    0,  160,    0,  158,    0,    0,  159,
        0,    0,  161,    0,  165,  165,  165,    0,  164,  159,
      160,  163,    0,  162,  166,  166,  166,    0,  164,  167,
      167,  167,    0,  160,  168,  168,  168,  163,  169,  169,
      169,    0,  170,  170,  170,    0,    0,  164,  166,  166,
      163,  165,  171,  171,  171,    0,    0,  168,  172,  172,
      172,  166,  169,    0,    0,    0,  167,    0,  170,    0,
        0,  168,  173,  173,  173,  169,    0,  166,  166,  170,

      174,  174,  174,    0,  173,    0,  168,    0,    0,  171,
        0,  169,  176,  176,  176,  172,    0,  170,  175,  175,
      175,  177,  177,  177,  178,  178,  178,    0,  174,  173,
      179,  179,  179,    0,  173,  176,    0,  174,  180,  180,
      180,    0,    0,  175,    0,  177,    0,    0,    0,  176,
      181,  181,  181,    0,    0,  175,    0,  174,  177,    0,
        0,  178,    0,    0,  176,    0,    0,  179,  182,  182,
      182,  181,  175,    0,  177,  180,    0,  183,  183,  183,
      184,  184,  184,  182,  185,  185,  185,  181,  186,  186,
      186,  187,  187,  187,  188,  188,  188,  189,  189,  189,

      181,  184,    0,    0,    0,  182,  190,  190,  190,  189,
      191,  191,  191,  182,  183,    0,    0,  184,  192,  192,
      192,  185,  193,  193,  193,  186,    0,    0,  187,    0,
      184,  188,    0,    0,  189,  194,  194,  194,    0,  189,
        0,    0,    0,  190,  195,  195,  195,  191,  193,  196,
      196,  196,  197,  197,  197,  192,  198,  198,  198,  193,
        0,    0,  195,  199,  199,  199,  200,  200,  200,  201,
      201,  201,  194,  202,  202,  202,    0,  193,  200,    0,
        0,  195,  203,  203,  203,    0,  196,  201,    0,  197,
        0,  195,    0,  198,  204,  204,  204,  205,  205,  205,

      199,    0,    0,  200,    0,    0,  201,    0,  200,    0,
      202,  206,  206,  206,    0,    0,  201,    0,    0,  203,
      207,  207,  207,  208,  208,  208,  209,  209,  209,    0,
        0,  204,    0,    0,  205,    0,    0,  206,  210,  210,
      210,  211,  211,  211,  212,  212,  212,    0,  206,  213,
      213,  213,  214,  214,  214,    0,    0,  207,    0,    0,
      208,    0,  210,  209,    0,    0,  206,    0,    0,    0,
        0,    0,    0,    0,    0,  210,    0,    0,  211,    0,
      213,  212,    0,    0,    0,    0,  213,    0,    0,  214,
        0,  210,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,  213,
      216,  216,  216,  216,  216,  217,  217,  217,  217,  217,
      218,  218,  219,    0,  219,  219,  219,  220,    0,  220,
      221,    0,  221,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,

      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[93] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexico.l"
#line 5 "lexico.l"
#include <iostream>
#include <QString>
#include "parser.h"

#include <string>
#include <QList>

    int yylex();
    void yyerror(const char *s);
    int linea = 0;
    int columna = 1;
    int anterior = 0;



#line 928 "scanner.cpp"

#define INITIAL 0
#define COM 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 44 "lexico.l"


#line 1148 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 216 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1534 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 46 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmkdisk;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 47 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return prmdisk;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 48 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pfdisk;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmount;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 50 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pumount;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmkfs;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 52 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return plogin;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 53 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return plogout;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 54 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmkgrp;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 55 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return prmgrp;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 56 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmkusr;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 57 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return prmusr;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 58 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pchmod;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 59 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return ptouch;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 60 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pcat;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 61 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return prm;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 62 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pedit;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 63 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pren;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 64 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmkdir;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 65 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pcp;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 66 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pmv;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 67 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pfind;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 68 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pchown;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 69 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pchgrp;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 70 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pPause;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 71 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return pexec;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 72 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return prep;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 76 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return psize;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 77 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pF;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 78 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pU;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 79 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pR;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 80 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pP;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 81 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 82 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 83 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pK;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 84 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pM;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 85 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pB;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 86 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pPath;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 87 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return ptype;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 88 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pdelete;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 89 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pname;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 90 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return padd;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 91 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pid;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 92 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pfs;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 93 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return puser;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 94 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pPwd;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 95 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pusr;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 96 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pgrp;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 97 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pugo;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 98 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pcont;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 99 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pstdin;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 100 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pfilen;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 101 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pdest;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 102 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pruta;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 103 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return proot;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 104 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pBf;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 105 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pWf;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 106 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pFf;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 107 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return pfile;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 108 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return precovery;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 109 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return ploss;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 110 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return fast;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 111 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return full;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 112 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return ext2;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 113 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext); strcpy(yylval.TEXT, yytext);return ext3;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 117 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return entero;}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 118 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return cadena;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 119 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return identificador;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 120 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return caracter;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 121 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return tpath;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 124 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return punto;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 125 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return bracketabre;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 126 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return bracketcierra;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 127 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return corcheteabre;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 128 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return corchetecierra;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 129 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return puntocoma;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 130 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return potencia;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 131 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return coma;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 132 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return parentesisabre;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 133 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return parentesiscierra;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 134 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return llaveabre;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 135 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return llavecierra;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 136 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return mas;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 137 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return menos;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 138 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return multiplicacion;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 139 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return igual;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 140 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return dolar;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 141 "lexico.l"
{columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);return dospuntos;}
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 143 "lexico.l"
{linea++; columna=0; anterior=0;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 144 "lexico.l"
{ columna++; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 148 "lexico.l"
{

std::cout<<"Error Lexico: "<<linea<<"\n";
//printf("Error lexico en linea %d",linea);
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 153 "lexico.l"
ECHO;
	YY_BREAK
#line 1681 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COM):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 216 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 216 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 215);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 153 "lexico.l"
